import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "./components/NavBar";
import { MyContextProvider } from "./context/BankContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "App Next Quo",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[while]">
      <body className={inter.className}>
        <NavBar></NavBar>
        <MyContextProvider>{children}</MyContextProvider>
      </body>
    </html>
  );
}
